package 第十一章.实例116;
/*
 * Generated by XDoclet - Do not edit!
 */
package cal;

/**
 * Local interface for Calculate.
 * @lomboz generated
 */
public interface CalculateLocal
   extends javax.ejb.EJBLocalObject
{

}
