package 第十一章.实例116;
/*
 * Generated by XDoclet - Do not edit!
 */
package cal;

/**
 * Session layer for Calculate.
 * @lomboz generated
 */
public class CalculateSession
   extends cal.CalculateBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
