package 第十一章.实例116;
/*
 * Generated by XDoclet - Do not edit!
 */
package cal;

/**
 * Remote interface for Calculate.
 * @lomboz generated
 */
public interface Calculate
   extends javax.ejb.EJBObject
{

   public int add( int a,int b )
      throws java.rmi.RemoteException;

}
