package 第十一章.实例116;
/*
 * Generated by XDoclet - Do not edit!
 */
package cal;

/**
 * Home interface for Calculate.
 * @lomboz generated
 */
public interface CalculateHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Calculate";
   public static final String JNDI_NAME="CalculateBean";

   public cal.Calculate create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
