package 第十一章.实例116;
/*
 * Generated by XDoclet - Do not edit!
 */
package cal;

/**
 * Local home interface for Calculate.
 * @lomboz generated
 */
public interface CalculateLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CalculateLocal";
   public static final String JNDI_NAME="CalculateLocal";

   public cal.CalculateLocal create()
      throws javax.ejb.CreateException;

}
