package 第十四章.实例136;
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestDLL */

#ifndef _Included_TestDLL
#define _Included_TestDLL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestDLL
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestDLL_helloWorld
  (JNIEnv *, jclass);

/*
 * Class:     TestDLL
 * Method:    cTOJava
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestDLL_cTOJava
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
